# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_plainText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plainText.setGeometry(QtCore.QRect(140, 120, 581, 121))
        self.txt_plainText.setObjectName("txt_plainText")
        self.txt_cipherText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipherText.setGeometry(QtCore.QRect(140, 330, 581, 131))
        self.txt_cipherText.setObjectName("txt_cipherText")
        self.cipherText = QtWidgets.QLabel(self.centralwidget)
        self.cipherText.setGeometry(QtCore.QRect(50, 330, 61, 16))
        self.cipherText.setObjectName("cipherText")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(230, 490, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.key = QtWidgets.QLabel(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(80, 270, 31, 16))
        self.key.setObjectName("key")
        self.txt_key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(140, 270, 581, 31))
        self.txt_key.setObjectName("txt_key")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 60, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lb_plainText = QtWidgets.QLabel(self.centralwidget)
        self.lb_plainText.setGeometry(QtCore.QRect(50, 120, 61, 16))
        self.lb_plainText.setObjectName("lb_plainText")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(520, 490, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "VIGENERE CIPHER"))
        self.cipherText.setText(_translate("MainWindow", "Cipher Text:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.key.setText(_translate("MainWindow", "Key:"))
        self.label_5.setText(_translate("MainWindow", "Đặng Ngọc Đức - 2380600525"))
        self.lb_plainText.setText(_translate("MainWindow", "Plain Text:"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
